### ISSUE TITLE
Some Suggestions for the AVcleaner tool

### ISSUE THREAD

**Issue by khansaad1275** [RedQueen979/AVcleaner#1]
![image](https://github.com/RedQueen979/AVcleaner/assets/32749921/ee0732b0-2515-47b7-a785-ad4f5030df3d)

I like the idea that we are trying to clear data inside the temp folder and using the apt-get clean command to clear the local repository but In the process the code is leaving a log file in the home folder and it creates mess. further more, after checking the data inside cat file, i found information like which data got deleted, insted i saw these 3 lines

Cleaned cached packages.
Cleaned temporary files.
Cleaned unnecessary logs.

I hope you will fix all this soon coz this tool can be really helpful.

**Comment by RedQueen979** [comment]
Done!  Now you can see all your deleted junk files in `cleanup_log.txt`

Thank you for raising the issue! I'm thrilled to let you know that your feedback helped me solve it. This being my first tool and you being the first user, it's a special milestone. Your support means a lot. If you have more insights or encounter anything else, don't hesitate to reach out. Much appreciated!
